image: lcxat/ruby-wagon-cypress

before_script:
  - npm install
cypress:
  script:
    - npm test
  artifacts:
    paths:
      - /builds/<group>/<project>/cypress/screenshots/
      - /builds/<group>/<project>/cypress/videos/