image: lcxat/ruby-wagon-cypress

cache: 
  key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
  paths:
    - node_modules/
    - cypress/
before_script:
  - npm install
cypress:

  script:
    - ./node_modules/.bin/cypress run
  only:
    changes:
      - package-lock.json
  artifacts:
    paths:
      - /builds/<group>/<project>/cypress/screenshots/
      - /builds/<group>/<project>/cypress/videos/