image: lcxat/ruby-wagon-cypress

stages:
  - status
  - update
  - build
  - test
  - deploy
before_script:
#  - npm install
  - npm install cypress

cache: 
  key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
  paths:
    - node_modules/
    - cypress/  

statusCode:
  stage: status
  script: 
    - git status

whereAmI:
  stage: status
  script: 
    - pwd

whatISee:
  stage: status
  script: 
    - ls -rtl

updateCode:
  stage: update
  script: 
    - git pull origin master

buildReactApp:
  stage: build
  script:
    - npm run build

deployApp:
  stage: deploy
  script:
    - firebase deploy
cypresse:
  stage: test
  script:
    - ./node_modules/.bin/cypress run
  #only:
  #  changes:
  #    - package-lock.json
  artifacts:
    paths:
      - /builds/<group>/<project>/cypress/screenshots/
      - /builds/<group>/<project>/cypress/videos/